# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: false
language: python

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: pypy
      env: TOXENV=pypy
install:
- pip install tox
- pip install python-coveralls
- pip install codecov
- pip install -r requirements_dev.txt
script:
- tox
after_success:
- codecov
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sbuss
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: sbuss/multiaddr
    branch: master
    condition: $TOXENV == py27
